// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAikSFMX0z_Agbs6HOHAlS6EFobRyBej5c',
    appId: '1:211101276863:web:c17b0867f5952ddd20040a',
    messagingSenderId: '211101276863',
    projectId: 'nusawashlaundry-efd17',
    authDomain: 'nusawashlaundry-efd17.firebaseapp.com',
    storageBucket: 'nusawashlaundry-efd17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMzXp6omq4nvNgTEI2cQ8WfPYo4BKXdKw',
    appId: '1:211101276863:android:909a628a9ae2ecbb20040a',
    messagingSenderId: '211101276863',
    projectId: 'nusawashlaundry-efd17',
    storageBucket: 'nusawashlaundry-efd17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCehZ5ALJtZUX8TE4nFGjmySY8b7GIRx98',
    appId: '1:211101276863:ios:993495d97e85a9d120040a',
    messagingSenderId: '211101276863',
    projectId: 'nusawashlaundry-efd17',
    storageBucket: 'nusawashlaundry-efd17.appspot.com',
    iosBundleId: 'com.nusawashlaundry.nusaWashLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCehZ5ALJtZUX8TE4nFGjmySY8b7GIRx98',
    appId: '1:211101276863:ios:993495d97e85a9d120040a',
    messagingSenderId: '211101276863',
    projectId: 'nusawashlaundry-efd17',
    storageBucket: 'nusawashlaundry-efd17.appspot.com',
    iosBundleId: 'com.nusawashlaundry.nusaWashLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAikSFMX0z_Agbs6HOHAlS6EFobRyBej5c',
    appId: '1:211101276863:web:cd0741e9b7b9f88120040a',
    messagingSenderId: '211101276863',
    projectId: 'nusawashlaundry-efd17',
    authDomain: 'nusawashlaundry-efd17.firebaseapp.com',
    storageBucket: 'nusawashlaundry-efd17.appspot.com',
  );
}
